ConfigVersion:
#If RespectGriefPrevention is true, it will allow a player to use all animals inside a claim they have access trust to.
RespectGriefPrevention: false
#If ProtectTames is true, it will protect the tamed mobs of players from being damaged by players other than the owner.
ProtectTames: true
#If Allow Transfers is true, it will allow players with the appropriate permission to transfer their own tames.
AllowTransfers: true
#If AllowReleases is true, it will allow players with appropriate permission to release their own animals.
AllowReleases: true
#If ProtectHorses is true, players will not be able to ride another player's horse or open horse inventory.
ProtectHorses: true
#If AllowHorseDye is true, players will be able to manipulate the colors of their horses using Dye.
AllowHorseDye: true
#Toggling any of the Breeding Options to false will make it so players cannot breed that animal. (Tamed Animals Only)
Breeding:
  Horse: true
  Wolf: true
  Ocelot: true

messages:
  Prefix: "&7[&6TameManagement&7] "
  commands:
    noPermission: "&cYou do not have permission to do that."
    setVariant: "&aRight click the horse that you would like to change to a %variant."
    setColor: "&aRight click a horse to change its color to %color."
    claim: "&aRight click the horse you would like to claim."
    invoked: "&aYou have invoked &3%amount %mob."
    configReloaded: "&aConfig reloaded."
    releaseNotAllowed: "&cThis server does not allow animals to be released."
    transfersNotAllowed: "&cThis server does not allow animal ownership to be transferred."
    releaseMessage: "&aYou have released this animal to the wild."
    playerNotOnline: "&cThat player is not online."
    cantTransferOwnershipToSelf: "&cYou can't transfer ownership of an animal to yourself."
    transferMessage: "&aOwnership of this animal transferred to &3newowner."
  listener:
    animalDoesNotBelongToYou: "&cYou can't damage an animal that doesn't belong to you."
    horseAlreadyOwned: "&cThis horse is already owned by &3%owner&c."
    cantInteractWithHorse: "&cYou can't interact with a horse belonging to &3&owner&c."
    cantChangeStyle: "You can't change the style on &3%owner's &chorse."
    styleChanged: '&aHorse style changed.'
    cantChangeColor: "&cYou can't change the color of &3%owner's &chorse."
    colorChanged: '&aHorse color changed.'
    cantChangeVariant: "&cYou can't change the variant of &3%owner's &chorse."
    changedVariant: '&aHorse variation changed.'
    doesNotOwn: "&cThis animal belongs to &3%owner&c."
    animalReleased: '&aYou have released this animal to the wild.'
    animalTransferred: "&aYou have transferred this animal to &3%newowner"
    horseClaimed: "&aYou now own this horse."